MSG_ALL_QUIT = "RU.Stop.All"
MSG_LOQ_PLAY = "RU.S1.Output.Plan.Task.Speech.Play"    
MSG_LOQ_QUEUE = "RU.S1.Output.Plan.Task.Speech.Queue"    
MSG_LOQ_QUEUE_MISSING = "RU.S1.Output.Plan.Task.Speech.Queue.Missing"    
MSG_LOQ_INJECT = "RU.S1.Output.Plan.Task.Speech.Inject"    
MSG_LOQ_PAUSE = "RU.S1.Internal.Instruct.Speech.Pause"    
MSG_LOQ_STOP = "RU.S1.Internal.Instruct.Speech.Stop"    
MSG_LOQ_STOP_EXECUTED = "RU.S1.Internal.Instruct.Speech.Stop.Executed"    
MSG_LOQ_MISSING_TEXT = "RU.S1.Intrnal.Instruct.Speech.Missing"    
MSG_LOQ_RESUME = "RU.S1.Internal.Instruct.Speech.Resume"    
MSG_LOQ_VOLUME = "RU.S1.Internal.Instruct.Speech.Volume"    
MSG_LOQ_PITCH = "RU.S1.Internal.Instruct.Speech.Pitch"    
MSG_LOQ_SPEED = "RU.S1.Internal.Instruct.Speech.Speed"    
MSG_LOQ_VOICE = "RU.S1.Internal.Instruct.Speech.Voice"    
MSG_LOQ_SENTENCE_REMOVE = "RU.S1.Internal.Instruct.Speech.Sentence.Remove"    
MSG_LOQ_SENTENCE_FLUSH = "RU.S1.Internal.Instruct.Speech.Sentence.Flush"    
MSG_LOQ_SPEED_RANGE = "RU.S1.Internal.Instruct.Speech.Speed.Range"    
MSG_LOQ_PITCH_RANGE = "RU.S1.Internal.Instruct.Speech.Pitch.Range"    
MSG_LOQ_VOLUME_RANGE = "RU.S1.Internal.Instruct.Speech.Volume.Range"    
MSG_LOQ_SENTENCE_PROSODY_REMOVE = "RU.S1.Internal.Instruct.Speech.Sentence.Prosody.Remove"    
MSG_LOQ_SENTENCE_PROSODY_REPLACE = "RU.S1.Internal.Instruct.Speech.Sentence.Prosody.Replace"    
MSG_LOQ_PROSODY_REPLACE = "RU.S1.Internal.Instruct.Speech.Prosody.Replace"    

MSG_LOQ_REPLY_SPEECH_DONE = "P1.CP.stop" #"RU.S1.Output.Plan.Task.Speech.Done"    
MSG_LOQ_REPLY_SENTENCE_DONE = "RU.S1.Output.Plan.Task.Speech.SentenceDone"    
MSG_LOQ_REPLY_PLAY_ACK = "RU.S1.Output.Plan.Task.Speech.Play.Ack"    
MSG_LOQ_REPLY_BOOKMARK = "RU.S1.Output.Plan.Task.Speech.Bookmark"    

#MSG_SPEECH_ON = "SpeechOn" #"RU.Input.PitchTracker.Speech.On"    
#MSG_SPEECH_OFF = "SpeechOff" #"RU.Input.PitchTracker.Speech.Off"    
MSG_SPEECH_ON = "P1.start" #"RU.Input.PitchTracker.Speech.On"    
MSG_SPEECH_OFF = "P1.stop" #"RU.Input.PitchTracker.Speech.Off"   
MSG_SPEECH_ON = "P1.start" #"RU.Input.PitchTracker.Speech.On"    
MSG_SPEECH_OFF = "P1.stop" #"RU.Input.PitchTracker.Speech.Off"   

#Content Generator
MSG_CG_NEXT = "RU.S1.Internal.Instruct.Content.Start"    
MSG_CG_REPEAT = "RU.S1.Internal.Instruct.Content.Repeat.Last"    
MSG_CG_BYTYPE = "RU.S1.Internal.Instruct.Content.By.Type"    
MSG_CG_QUERY = "RU.S1.Internal.Query.Content.Ready"    
MSG_CG_WRAPUP = "RU.S1.Internal.Instruct.Content.Stop"    
MSG_CG_PREPARE = "RU.S1.Internal.Instruct.Content.Prepare"    
MSG_CG_HAVESOMETHINGTOSAY = "RU.S1.Internal.Instruct.Content.Ready"    
#MSG_CG_CONTENT_COMPLETE = "RU.S1.Internal.Instruct.Content.Complete"    
MSG_INT_RECOGNITION = "RU.S1.Internal.Instruct.Interview.Match.Response"     
#"RU.S1.Input.Perception.Hear.Keyword"    
MSG_CG_ADD_SENTENCE = "RU.S1.Input.Sentence.New"    

MSG_PA_OVERLAP_START = "RU.S1.Perception.Pitch.Overlapping.Start"    
MSG_PA_OVERLAP1_START = "RU.S1.Perception.Pitch.Overlapping.Start.1"    
MSG_PA_OVERLAP2_START = "RU.S1.Perception.Pitch.Overlapping.Start.2"    
MSG_PA_OVERLAP_STOP = "RU.S1.Perception.Pitch.Overlapping.Duration"    
