	<variable name="AppDir" value="." />
	<variable name="HTMLDir" value="ccmhtml" />
	<variable name="PylibDir" value="./" />
	<variable name="PsyDir" value="./" />
	<variable name="DataDir" value="./Data" />
	<variable name="RecordingDir" value="./Recordings" /> 
	<variable name="SystemID" value="1" /> 

	<variable name="FaceServerAddress" value="10.2.21.17" /> 
	<variable name="FaceServerPort" value="3500" /> 
	<variable name="FaceServerUsername" value="Admin@Admin" /> 
	<variable name="FaceServerPassword" value="@@@dmin" /> 

	<variable name="initpose_x" value="0.052" /> 
	<variable name="initpose_y" value="-0.318" /> 
	<variable name="initpose_oz" value="-0.070" /> 
	<variable name="initpose_ow" value="0.998" /> 
	<variable name="MasterAddress" value="localhost" />
	<variable name="MasterPort" value="10000" />

	<variable name="PanelPoint1Data" value="-2.378, -3.293, -0.594, 0.804"/>
	<variable name="PanelPoint2Data" value="-4.014, -2.898, 0.964, -0.263" />

	<variable name="InputAudioDevice" value="Jabra" />
	<variable name="OutputAudioDevice" value="Jabra" />
	<variable name="NuanceTTSEngine" value="ve_engine" />
	<variable name="NuanceVoconModels" value="models" />

	<variable name="SimulateSystem" value="Yes" />


<variable name="VantagePoint1Name" value="INTERACTION" />
<variable name="VantagePoint1Data" value="-1.020, -0.328, 0.412, 0.892" />
<variable name="VantagePoint1Overlap" value="1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0" />
<variable name="VantagePoint2Name" value="SEARCH 1" />
<variable name="VantagePoint2Data" value="-1.668, -1.920, 0.984, -0.180" />
<variable name="VantagePoint2Overlap" value="1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0" />
<variable name="VantagePoint3Name" value="SEARCH 2" />
<variable name="VantagePoint3Data" value="-3.758, -1.324, -0.617, 0.787" />
<variable name="VantagePoint3Overlap" value="1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0" />
<variable name="VantagePoint4Name" value="SEARCH 3" />
<variable name="VantagePoint4Data" value="-3.791, -1.04, -0.004, 0.999" />
<variable name="VantagePoint4Overlap" value="1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0" />
<variable name="VantagePoint5Name" value="SEARCH 4" />
<variable name="VantagePoint5Data" value="-1.976, 1.750, -0.722, -0.692" />
<variable name="VantagePoint5Overlap" value="1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0" />
<variable name="VantagePoint6Name" value="SEARCH 5" />
<variable name="VantagePoint6Data" value="-2.679, -0.845, 0.623, 0.782" />
<variable name="VantagePoint6Overlap" value="1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0" />
<variable name="VantagePoint7Name" value="SEARCH 6" />
<variable name="VantagePoint7Data" value="-3.046, -2.178, -0.758, 0.651" />
<variable name="VantagePoint7Overlap" value="0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0" />
